<?php

$this->layout()->breadcrumb = $this->breadcrumb([
	['Points of Sale', $this->url('point-of-sale')],
	[$this->form->get('name')->getValue()]
]);
$this->layout()->actions = '<li><a href="' . $this->url('point-of-sale') . '" class="btn btn-primary">Back</a></li>';
$this->headTitle($this->form->get('name')->getValue());
$this->layout()->pageTitle = $this->form->get('name')->getValue();

?>

<?php echo $this->form()->openTag($this->form); ?>

<fieldset>
	<legend>General</legend>

	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
		<div class="col-sm-2">
			<?php echo $this->formInput($this->form->get('name')); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="address" class="col-sm-2 control-label">Address</label>
		<div class="col-sm-4">
			<?php echo $this->formInput($this->form->get('address')); ?>
		</div>
	</div>
</fieldset>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
