<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Juno')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
	        ->prependStylesheet($this->basePath() . '/css/main.css')
            ->prependStylesheet($this->basePath() . '/css/jquery.dataTables.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
	        ->prependStylesheet($this->basePath() . '/css/selectize.css')
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
	        ->prependFile($this->basePath() . '/js/dataTables.bootstrap.js')
	        ->prependFile($this->basePath() . '/js/jquery.dataTables.min.js')
	        ->prependFile($this->basePath() . '/js/selectize.min.js')
	        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
	        ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span class="navbar-brand">
	                    <a href="<?php echo $this->url('home') ?>">Juno</a>
                    </span>
                </div>
	            <?php if ($this->ident()) { ?>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('product'); ?>">Products</a></li>
                        <li><a href="<?php echo $this->url('point-of-sale'); ?>">Points of Sell</a></li>
                        <li><a href="<?php echo $this->url('warehouse'); ?>">Warehouses</a></li>
                        <li><a href="#">Statistics</a></li>
                        <li><a href="#"><span class="label label-success">Make a Sale</span></a></li>
                    </ul>
	                <ul class="nav navbar-nav pull-right">
		                <li>
			                <a href="#" class="dropdown-toggle" id="profile-dropdown" data-toggle="dropdown">
				                <img src="http://www.gravatar.com/avatar/<?php echo md5($this->ident()->email); ?>" width="20">
				                <?php echo $this->ident()->name; ?> <span class="caret"></span>
			                </a>
			                <ul class="dropdown-menu" role="menu" aria-labelledby="profile-dropdown">
				                <li><a role="menuitem" tabindex="-1" href="<?php echo $this->url('user'); ?>">User Management</a></li>
				                <li><a role="menuitem" tabindex="-1" href="#">Settings</a></li>
				                <li class="divider"></li>
				                <li><a href="<?php echo $this->url('logout') ?>">Logout</a></li>
			                </ul>
		                </li>
	                </ul>
                </div>
	            <?php } ?>
            </div>
        </nav>
        <div class="container">
	        <?php if ($this->ident()) { ?>
	        <div class="row">
		        <div class="col-xs-12">
			        <?php echo $this->layout()->breadcrumb; ?>

			        <?php
			        $flash = $this->flashMessenger();
			        $flash->setMessageOpenFormat('
<div%s>
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
	    &times;
	</button>
<div>
			        ')->setMessageCloseString('</div></div>');

			        echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
			        echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
			        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
			        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));

			        ?>
		        </div>

		        <div class="col-xs-12">
			        <ul class="list-inline pull-right">
				        <?php echo $this->layout()->actions; ?>
			        </ul>
			        <h1 class="general-title"><?php echo $this->layout()->pageTitle; ?></h1>
		        </div>
	        </div>
	        <?php } ?>

            <?php echo $this->content; ?>
        </div>
        <div class="container">
	        <hr>
	        <footer>
		        <p>&copy; <?php echo date('Y') ?> by <a href="http://jiromm.com/" target="_blank">Aram Baghdasaryan</a>. All rights reserved.</p>
	        </footer>
        </div>
	        <?php echo $this->inlineScript()
		        ->prependFile($this->basePath() . '/js/custom.js')
	        ; ?>
    </body>
</html>
