<?php

$this->layout()->breadcrumb = $this->breadcrumb([
	['Warehouses', $this->url('warehouse')],
	['Add Warehouse'],
]);
$this->layout()->actions = '<li><a href="' . $this->url('warehouse') . '" class="btn btn-primary">Back</a></li>';
$this->headTitle('Add Warehouse');
$this->layout()->pageTitle = 'Add Warehouse';

?>

<?php echo $this->form()->openTag($this->form); ?>

<fieldset>
	<legend>General</legend>

	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
		<div class="col-sm-2">
			<?php echo $this->formInput($this->form->get('name')); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="address" class="col-sm-2 control-label">Address</label>
		<div class="col-sm-4">
			<?php echo $this->formInput($this->form->get('address')); ?>
		</div>
	</div>
</fieldset>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
