<?php

$this->layout()->breadcrumb = $this->breadcrumb([
	['Products', $this->url('product')],
	['Add Product'],
]);
$this->layout()->actions = '<li><a href="' . $this->url('product') . '" class="btn btn-primary">Back</a></li>';
$this->headTitle('Add Product');
$this->layout()->pageTitle = 'Add Product';

?>

<?php echo $this->form()->openTag($this->form); ?>

<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
	<div class="col-sm-4">
		<?php echo $this->formInput($this->form->get('name')); ?>
	</div>
</div>

<div class="form-group">
	<label for="quantity" class="col-sm-2 control-label">Quantity <?php echo $this->required(); ?></label>
	<div class="col-sm-1">
		<?php echo $this->formInput($this->form->get('quantity')); ?>
	</div>
</div>

<div class="form-group">
	<label for="product_type_id" class="col-sm-2 control-label">Product Type <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formSelect($this->form->get('product_type_id')); ?>
	</div>
</div>

<div class="form-group">
	<label for="direction" class="col-sm-2 control-label">Direction <?php echo $this->required(); ?></label>
	<div class="col-sm-3">
		<?php echo $this->formSelect($this->form->get('direction')); ?>
	</div>
</div>

<div class="form-group">
	<label for="description" class="col-sm-2 control-label">Description</label>
	<div class="col-sm-10">
		<?php echo $this->formTextarea($this->form->get('description')); ?>
	</div>
</div>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
