<?php

$this->layout()->breadcrumb = $this->breadcrumb([
	['Products', $this->url('product')],
	['Manage Product'],
]);
$this->layout()->actions = '<li><a href="' . $this->url('product') . '" class="btn btn-primary">Back</a></li>';
$this->headTitle('Manage Product');
$this->layout()->pageTitle = 'Manage Product';

$productProperties = $this->productProperties;

?>

<?php echo $this->form()->openTag($this->form); ?>

<fieldset>
	<legend>General</legend>

	<div class="form-group">
		<label for="name" class="col-sm-2 control-label">Name <?php echo $this->required(); ?></label>
		<div class="col-sm-4">
			<?php echo $this->formInput($this->form->get('name')); ?>
		</div>
	</div>

	<div class="form-group">
		<label for="quantity" class="col-sm-2 control-label">Quantity <?php echo $this->required(); ?></label>
		<div class="col-sm-1">
			<?php echo $this->formInput($this->form->get('quantity')); ?>
		</div>
	</div>
</fieldset>

<?php if (count($productProperties)) { ?>
	<fieldset>
		<legend>Properties</legend>

		<?php $index = 1; ?>
		<?php foreach ($productProperties as $property) { ?>
			<div class="form-group">
				<label for="property<?php echo $index; ?>" class="col-sm-2 control-label"><?php echo $property['name']; ?></label>
				<div class="col-sm-2">
					<div class="input-group">
						<?php echo $this->formInput($this->form->get('property' . $index)); ?>
						<span class="input-group-addon"><?php echo $property['type']; ?></span>
					</div>
				</div>
			</div>
			<?php $index++; ?>
		<?php } ?>
	</fieldset>
<?php } ?>

<div class="form-group">
	<div class="col-sm-offset-2 col-sm-2">
		<?php echo $this->formSubmit($this->form->get('submit')); ?>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
